module.exports = {
	DEFAULT_NODE : 0,
	HTTP_ENDPOINT_NODE : 1,
	HTTP_OUTPUT_NODE : 2,
	HTTP_REDIRECT_NODE : 3,
	DEPENDENCY : 4,
	FUNCTION_NODE : 5,
	FUNCTION_INPUT_NODE : 6,
	FUNCTION_OUTPUT_NODE : 7,
	MODEL_NODE : 8,
	FORWARD_NODE : 9
}